import {
  Tenant,
  User,
  Patient,
  Anamnesis,
  SessionPackage,
  Session,
  ClinicalEvolution,
  DocumentFile,
  SignatureRecord,
  PublicValidationToken,
  AuditLog,
} from '../types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-demo-1',
    name: 'Clínica Fisio & Terapia Integrada',
    tradeName: 'Clínica Fisio & Terapia Integrada',
    corporateName: 'Fisio & Terapia Integrada LTDA',
    docType: 'CNPJ',
    documentNumber: '12.345.678/0001-90',
    email: 'contato@fisioterapia.com.br',
    phone: '(11) 99999-8888',
    cep: '01310-100',
    address: 'Avenida Paulista',
    number: '1000',
    complement: 'Sala 302',
    neighborhood: 'Bela Vista',
    city: 'São Paulo',
    state: 'SP',
    country: 'Brasil',
    logoUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=200&auto=format&fit=crop&q=80',
    primaryColor: '#0d9488',
    secondaryColor: '#0f766e',
    themeMode: 'light',
    customHeader: 'Clínica Fisio & Terapia Integrada - Fisioterapia e Massoterapia',
    publicPageTitle: 'Clínica Fisio & Terapia Integrada',
    supportEmail: 'contato@fisioterapia.com.br',
    supportPhone: '(11) 99999-8888',
    creatorName: 'osaiasbrito',
    whatsappConfig: {
      token: 'whatsapp_token_configured',
      phoneNumberId: '1092837465',
      status: 'CONFIGURED',
    },
    createdAt: '2026-08-19T02:00:00.000Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-super-osaias',
    tenantId: 'tenant-demo-1',
    name: 'osaiasbrito',
    email: 'osaiasbrito@gmail.com',
    role: 'ADMIN',
    accessMode: 'COMPREHENSIVE',
    specialty: 'Super Administrador do Sistema & Gestor Master',
    phone: '(98) 98854-1695',
    active: true,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    isSuperUser: true,
    createdAt: '2026-08-19T02:00:00.000Z',
  },
  {
    id: 'user-senhordispositivos',
    tenantId: 'tenant-demo-1',
    name: 'senhordispositivos',
    email: 'senhordispositivos@gmail.com',
    role: 'ADMIN',
    accessMode: 'COMPREHENSIVE',
    specialty: 'Administrador Geral',
    phone: '(98) 98854-1695',
    active: true,
    avatarUrl: '',
    isSuperUser: true,
    createdAt: '2026-08-19T02:00:00.000Z',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-thayna-farias',
    tenantId: 'tenant-demo-1',
    name: 'THAYNÁ GOMES FARIAS',
    cpf: '',
    phone: '(98) 99992-0949',
    whatsapp: '(98) 99992-0949',
    email: 'thayna.farias@email.com',
    profession: 'ADVOGADA',
    birthDate: '1980-01-05',
    cep: '65075-000',
    street: 'Rua das Palmeiras',
    number: '120',
    neighborhood: 'Renascença',
    city: 'São Luis',
    state: 'MA',
    referencePoint: 'Próximo ao Fórum',
    assignedProfessionalId: '',
    assignedProfessionalName: 'Geral',
    notes: 'Paciente cadastrado no sistema para acompanhamento terapêutico.',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'pat-sidney-leitao',
    tenantId: 'tenant-demo-1',
    name: 'SIDNEY LEITÃO',
    cpf: '123.456.789-00',
    phone: '(98) 98854-1695',
    whatsapp: '(98) 98854-1695',
    email: 'sidney.leitao@email.com',
    profession: 'Empresário',
    birthDate: '1985-06-15',
    cep: '65075-000',
    street: 'Avenida Litorânea',
    number: '500',
    neighborhood: 'Calhau',
    city: 'São Luis',
    state: 'MA',
    referencePoint: 'Próximo à praia',
    assignedProfessionalId: 'user-super-osaias',
    assignedProfessionalName: 'osaiasbrito',
    notes: 'Paciente com foco em relaxamento muscular e alívio de tensões.',
    createdAt: '2026-08-19T02:00:00.000Z',
    updatedAt: '2026-08-19T02:00:00.000Z',
  },
];

export const INITIAL_PACKAGES: SessionPackage[] = [
  {
    id: 'pkg-sidney-1',
    tenantId: 'tenant-demo-1',
    patientId: 'pat-sidney-leitao',
    patientName: 'SIDNEY LEITÃO',
    professionalId: 'user-super-osaias',
    professionalName: 'osaiasbrito',
    title: 'Pacote Massoterapia Clínica',
    treatmentType: 'Massoterapia Clínica & Relaxante',
    sessionCount: 5,
    completedCount: 0,
    price: 450,
    validityDate: '2026-11-19',
    status: 'ACTIVE',
    createdAt: '2026-08-19T02:05:00.000Z',
  },
  {
    id: 'pkg-sidney-2',
    tenantId: 'tenant-demo-1',
    patientId: 'pat-sidney-leitao',
    patientName: 'SIDNEY LEITÃO',
    professionalId: 'user-super-osaias',
    professionalName: 'osaiasbrito',
    title: 'Pacote Fisioterapia & Reabilitação',
    treatmentType: 'Fisioterapia Manual',
    sessionCount: 10,
    completedCount: 0,
    price: 800,
    validityDate: '2026-12-19',
    status: 'ACTIVE',
    createdAt: '2026-08-19T02:10:00.000Z',
  },
];

export const INITIAL_SESSIONS: Session[] = [];

