import { pgTable, text, boolean, integer, jsonb } from 'drizzle-orm/pg-core';

export const tenants = pgTable('tenants', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  tradeName: text('trade_name'),
  corporateName: text('corporate_name'),
  docType: text('doc_type'),
  documentNumber: text('document_number'),
  email: text('email'),
  phone: text('phone'),
  cep: text('cep'),
  address: text('address'),
  number: text('number'),
  complement: text('complement'),
  neighborhood: text('neighborhood'),
  city: text('city'),
  state: text('state'),
  country: text('country'),
  logoUrl: text('logo_url'),
  primaryColor: text('primary_color'),
  secondaryColor: text('secondary_color'),
  themeMode: text('theme_mode'),
  customHeader: text('custom_header'),
  publicPageTitle: text('public_page_title'),
  supportEmail: text('support_email'),
  supportPhone: text('support_phone'),
  creatorName: text('creator_name'),
  whatsappConfig: jsonb('whatsapp_config'),
  createdAt: text('created_at').notNull(),
});

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  role: text('role').notNull(),
  accessMode: text('access_mode').notNull(),
  specialty: text('specialty'),
  councilType: text('council_type'),
  councilNumber: text('council_number'),
  phone: text('phone'),
  active: boolean('active').default(true).notNull(),
  avatarUrl: text('avatar_url'),
  isSuperUser: boolean('is_super_user').default(false),
  createdAt: text('created_at').notNull(),
});

export const patients = pgTable('patients', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  name: text('name').notNull(),
  email: text('email'),
  cpf: text('cpf'),
  rg: text('rg'),
  gender: text('gender'),
  phone: text('phone').notNull(),
  whatsapp: text('whatsapp'),
  profession: text('profession'),
  birthDate: text('birth_date'),
  cep: text('cep'),
  street: text('street'),
  number: text('number'),
  complement: text('complement'),
  neighborhood: text('neighborhood'),
  city: text('city'),
  state: text('state'),
  referencePoint: text('reference_point'),
  notes: text('notes'),
  photoUrl: text('photo_url'),
  avatarUrl: text('avatar_url'),
  assignedProfessionalId: text('assigned_professional_id'),
  assignedProfessionalName: text('assigned_professional_name'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
});

export const anamneses = pgTable('anamneses', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  patientId: text('patient_id').notNull(),
  healthHistory: jsonb('health_history'),
  treatments: jsonb('treatments'),
  habits: jsonb('habits'),
  evaluation: jsonb('evaluation'),
  responsibilityTermAccepted: boolean('responsibility_term_accepted'),
  patientSignatureUrl: text('patient_signature_url'),
  city: text('city'),
  state: text('state'),
  signedAt: text('signed_at'),
  signedByIp: text('signed_by_ip'),
  createdAt: text('created_at').notNull(),
});

export const packages = pgTable('packages', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  patientId: text('patient_id').notNull(),
  patientName: text('patient_name'),
  professionalId: text('professional_id'),
  professionalName: text('professional_name'),
  title: text('title').notNull(),
  treatmentType: text('treatment_type'),
  sessionCount: integer('session_count').notNull(),
  completedCount: integer('completed_count').notNull(),
  price: integer('price').notNull(),
  validityDate: text('validity_date'),
  status: text('status').notNull(),
  clientSignatureUrl: text('client_signature_url'),
  clientConfirmedAt: text('client_confirmed_at'),
  signedTermUrl: text('signed_term_url'),
  signedAt: text('signed_at'),
  createdAt: text('created_at').notNull(),
});

export const sessions = pgTable('sessions', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  packageId: text('package_id'),
  isSingleSession: boolean('is_single_session'),
  price: integer('price'),
  patientId: text('patient_id').notNull(),
  patientName: text('patient_name').notNull(),
  professionalId: text('professional_id').notNull(),
  professionalName: text('professional_name').notNull(),
  sessionNumber: integer('session_number').notNull(),
  scheduledDate: text('scheduled_date').notNull(),
  scheduledTime: text('scheduled_time').notNull(),
  status: text('status').notNull(),
  bloodPressure: text('blood_pressure'),
  siNotes: text('si_notes'),
  procedures: jsonb('procedures'),
  evolutionText: text('evolution_text'),
  attendedAt: text('attended_at'),
  clientSignatureUrl: text('client_signature_url'),
  clientConfirmedAt: text('client_confirmed_at'),
  clientConfirmedIp: text('client_confirmed_ip'),
  validationToken: text('validation_token'),
  tokenExpiresAt: text('token_expires_at'),
  tokenUsedAt: text('token_used_at'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at'),
});

export const evolutions = pgTable('evolutions', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  patientId: text('patient_id').notNull(),
  sessionId: text('session_id'),
  professionalId: text('professional_id'),
  professionalName: text('professional_name'),
  date: text('date').notNull(),
  procedures: jsonb('procedures'),
  notes: text('notes').notNull(),
  bloodPressure: text('blood_pressure'),
  version: integer('version').default(1),
  createdAt: text('created_at').notNull(),
});

export const publicTokens = pgTable('public_tokens', {
  id: text('id').primaryKey(),
  token: text('token').notNull(),
  tenantId: text('tenant_id').notNull(),
  sessionId: text('session_id').notNull(),
  patientId: text('patient_id').notNull(),
  expiresAt: text('expires_at').notNull(),
  usedAt: text('used_at'),
  createdAt: text('created_at').notNull(),
});

export const auditLogs = pgTable('audit_logs', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  userId: text('user_id').notNull(),
  userName: text('user_name').notNull(),
  userRole: text('user_role'),
  action: text('action').notNull(),
  entity: text('entity').notNull(),
  entityId: text('entity_id').notNull(),
  ipAddress: text('ip_address'),
  result: text('result'),
  details: text('details').notNull(),
  timestamp: text('timestamp'),
});

export const documentFiles = pgTable('document_files', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  patientId: text('patient_id').notNull(),
  uploadedByUserId: text('uploaded_by_user_id'),
  uploadedByName: text('uploaded_by_name').notNull(),
  fileName: text('file_name').notNull(),
  fileType: text('file_type'),
  fileSize: integer('file_size'),
  fileUrl: text('file_url').notNull(),
  category: text('category').notNull(),
  notes: text('notes'),
  uploadedAt: text('uploaded_at').notNull(),
});

export const signatures = pgTable('signatures', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  patientId: text('patient_id').notNull(),
  patientName: text('patient_name'),
  documentType: text('document_type').notNull(),
  documentId: text('document_id'),
  referenceId: text('reference_id'),
  signatureUrl: text('signature_url').notNull(),
  signedByName: text('signed_by_name'),
  signedAt: text('signed_at').notNull(),
  ipAddress: text('ip_address').notNull(),
  hash: text('hash').notNull(),
});
